### ISSUE TITLE
WARNING  Unable to calculate transitive closures

### ISSUE THREAD

**Issue by sqal** [vercel/turborepo#10658]
### Verify canary release

- [x] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

Not available

### Which canary version will you have in your reproduction?

2.5.5-canary.0

### Environment information

```block
CLI:
   Version: 2.5.5-canary.0
   Daemon status: Running
   Package manager: bun

Platform:
   Architecture: aarch64
   Operating system: macos
   WSL: false

Environment:
   CI: None
   Terminal (TERM): xterm-256color
   Shell (SHELL): /bin/zsh
   stdin: false
```

### Expected behavior

I expect it to work without warning.

### Actual behavior

I see this warning every time I run the turbo command, locally or CI.

WARNING  Unable to calculate transitive closures: No lockfile entry found for '@emnapi/wasi-threads'.

### To Reproduce

1. Create a project using the startup repository according to the documentation: `bunx create-turbo@latest`
2. After installing it, go to the project and run a command, e.g. `bun run lint` - notice there's no warning right now
3. Run `cd web && bun add -d @tailwindcss/vite` - this is the dependency that causes the problem
4. Run `bun run lint` (from root ofc) - now you should see the warning

```
$ turbo run lint
turbo 2.5.5-canary.0

 WARNING  Unable to calculate transitive closures: No lockfile entry found for '@emnapi/core'
• Packages in scope: @repo/eslint-config, @repo/typescript-config, @repo/ui, docs, web
• Running lint in 5 packages
• Remote caching disabled
┌─ @repo/ui#lint > cache hit (outputs already on disk), replaying logs 0bc77abf29e562fe 

$ eslint . --max-warnings 0
└─ @repo/ui#lint ──
┌─ docs#lint > cache hit (outputs already on disk), replaying logs f73866bbc3d334ad 

$ next lint --max-warnings 0
✔ No ESLint warnings or errors
└─ docs#lint ──
┌─ web#lint > cache hit (outputs already on disk), replaying logs 495857fedc54924f 

$ next lint --max-warnings 0
✔ No ESLint warnings or errors
└─ web#lint ──

 Tasks:    3 successful, 3 total
Cached:    3 cached, 3 total
  Time:    61ms >>> FULL TURBO
```

### Additional context

As you can see It seems the problem is caused by @tailwindcss/vite. I've tested it with both the latest stable version (2.5.4) and the canary (2.5.5-canary.0), and the issue persists in both. I'm not sure whether the problem lies in @tailwindcss or in turbo.
I found only one [similar issue](https://github.com/vercel/turborepo/issues/9628) reported here, but the thread is quite old and suggests that the problem should have already been resolved in a previous release. Thanks for taking the time to look into this.

**Comment by arthberman** [comment]
+1

**Comment by zeyuri** [comment]
+1

**Comment by anthonyshew** [comment]
Hey, folks, it looks like Bun changed their lockfile format. We'll get a fix.

**Comment by vivym** [comment]
same.

**Comment by paul-vd** [comment]
> Hey, folks, it looks like Bun changed their lockfile format. We'll get a fix.

@anthonyshew any progress on this issue? I'm not sure where we can track it.

**Comment by anthonyshew** [comment]
This is the issue to watch.

**Comment by f1shy-dev** [comment]
+1 here!

**Comment by anthonyshew** [comment]
Folks, please try [v2.5.9-canary.0](https://github.com/vercel/turborepo/releases/tag/v2.5.9-canary.0) and let me know how it goes. It contains support for Bun's new lockfile format, and I'd love to have some early validation on it prior to marking Bun as stable in next release. These are hard to test in isolation. The best feedback comes through your real world usage.

Thank you for your support and patience on this. Please report back with your successes and failures.

If you are still experiencing trouble with that canary, please:
- Post here with the error you're seeing and a copy of/link to your lockfile.
  - If you are unable to post your lockfile/pruned output here but still want to provide it for the core team, please email it to me at anthony.shew@vercel.com so I can ensure we fix our parsing for your lockfile, specifically.

**Comment by leosilberg** [comment]
@anthonyshew thanks for the work to get bun compatibility, I'm still experiencing errors with `turbo prune --docker ` however. Sending via email the generated output json folder

**Comment by anthonyshew** [comment]
@leosilberg Thank you. Please include the original lockfile and the issue/error(s) you are seeing, as well, per the instructions above.

**Comment by Firgrep** [comment]
@anthonyshew 

Tested the canary version in a limited version of a larger project. Doesn't seem to pick up accurately on the dependencies.

Made a tiny repo here to reproduce the issue:
https://github.com/Firgrep/turborepo-bun-debug

There was a case where I forgot to update the lockfile after changing the version of a package (dayjs), causing the familiar lockfile has changed since you last updated package.json file error, and after I _just_ pushed the lockfile change, I got the correct affected package output. Maybe that's a clue to where the issue lies?

**Comment by anthonyshew** [comment]
@leosilberg I've released `v.2.5.9-canary.1` with changes that should help with your lockfile. Please give it a go and let me know how it goes. Appreciate you emailing.

---

@Firgrep, I tried your reproduction and I seem to be getting expected behavior.
```
▲ 👟 turborepo-bun-debug on main is 📦 v1.0.0
  turbo ct --affected
turbo 2.5.9-canary.0

• Packages in scope: //, @lib/deploy-ctl, app1, app2
• Running ct in 4 packages
• Remote caching disabled
app1:ct: cache miss, executing 8ab9152587792979
app1:ct:
app1:ct: $ tsc --pretty --noEmit
app2:ct: cache miss, replaying logs be4d08b2e059e7e2
@lib/deploy-ctl:ct: cache miss, replaying logs 740877a827dc8241
@lib/deploy-ctl:ct:
@lib/deploy-ctl:ct: $ tsc --noEmit
app2:ct:
app2:ct: $ tsc --pretty --noEmit

 Tasks:    3 successful, 3 total
Cached:    0 cached, 3 total
  Time:    538ms
```

Then, I changed the dayjs version in the root `package.json` to update the catalog for `dayjs`.

```
▲ 👟 turborepo-bun-debug on main is 📦 v1.0.0
  bun i
bun install v1.2.22 (6bafe260)

1 package installed [32.00ms]

▲ 👟 turborepo-bun-debug on main is 📦 v1.0.0
  turbo ct --affected
turbo 2.5.9-canary.0

• Packages in scope: //, @lib/deploy-ctl, app1, app2
• Running ct in 4 packages
• Remote caching disabled
@lib/deploy-ctl:ct: cache hit (outputs already on disk), replaying logs 740877a827dc8241
app2:ct: cache hit (outputs already on disk), replaying logs be4d08b2e059e7e2
app1:ct: cache miss, executing 3c0f2bd37d0bb2b7
@lib/deploy-ctl:ct:
@lib/deploy-ctl:ct: $ tsc --noEmit
app2:ct:
app2:ct: $ tsc --pretty --noEmit
app1:ct:
app1:ct: $ tsc --pretty --noEmit

 Tasks:    3 successful, 3 total
Cached:    2 cached, 3 total
  Time:    604ms
```

This is precisely the behavior I was hoping for. I tried some other iterations of a few things to see if I could introduce some breakage, but kept getting what I was looking for. What am I missing? 😄

**Comment by kade-robertson** [comment]
Unfortunately I can't provide a sample for this, but I came across this issue with 2.5.8 on a private repo and 2.5.9-canary.1 solved it for me.

**Comment by anthonyshew** [comment]
Thanks, @kade-robertson, appreciate the share. One step closer to stable!

**Comment by ben-hamel** [comment]
also ran into this issue trying out the BHVR stack https://bhvr.dev/getting-started

turborepo 2.5.9-canary.1 seemed to work

**Comment by Firgrep** [comment]
@anthonyshew Thank you for testing!

But in the example repo, `app2` does _not_ have `dayjs` as one of its dependencies. So why is `app2` being counted as one of the affected pkgs, if we update the `dayjs` version in the root `package.json`?

If I check out a new branch from main, make a change to `dayjs`, commit and run `turbo run ct --affected`, both apps still appear as affected, but I expected only one of them to be affected given the dependency.

Please correct me if I'm misunderstanding something here.

```
$ git checkout -b test/affected
Switched to a new branch 'test/affected'
$ git commit -m "test: dayjs ver"
$ turbo ct --affected
turbo 2.5.9-canary.0

• Packages in scope: //, @lib/deploy-ctl, app1, app2
• Running ct in 4 packages
• Remote caching disabled
app2:ct: cache miss, executing be4d08b2e059e7e2
app2:ct:
@lib/deploy-ctl:ct: cache hit, replaying logs 740877a827dc8241
@lib/deploy-ctl:ct:
@lib/deploy-ctl:ct: $ tsc --noEmit
app2:ct: $ tsc --pretty --noEmit
app1:ct: cache hit, replaying logs 8ab9152587792979
app1:ct:
app1:ct: $ tsc --pretty --noEmit

 Tasks:    3 successful, 3 total
Cached:    2 cached, 3 total
  Time:    763ms

```

**Comment by anthonyshew** [comment]
Update: @leosilberg provided another issue via email, which should be now fixed in [v2.5.9-canary.3](https://github.com/vercel/turborepo/releases/tag/v2.5.9-canary.3).

For those following this issue, let's be stress testing that version now. 🚀

**Comment by anthonyshew** [comment]
@Firgrep I see what's confusing about the behavior you're seeing. It's a subtlety with how `--affected` works. (I'll avoid going into depth about this, if I may, since it doesn't have to do with our lockfile parsing.) My fault for introducing that wrinkle to the testing.

Here is the set of commands I'm using to verify correctness on the provided repro repository. I'm able to run these repeatedly and get the expected behavior.
```bash
## Resetting source code changes and removing Turborepo's caches
git reset --hard HEAD && rm -rf .turbo apps/app1/.turbo apps/app2/.turbo lib/deploy-ctl/.turbo 

## Making sure we have the latest canary
bun i -D turbo@canary 

## Populate cache
bun turbo ct

## Update dependency in catalog manifest
jq --indent 4 '.workspaces.catalog.dayjs = "1.10.0"' package.json > tmp.json && mv tmp.json package.json

## Make sure changed dep is installed, updates lockfile
bun i 

## See what hits cache
bun turbo ct
```

The final `bun turbo ct` call results in:
```
▲ 👟 turborepo-bun-debug on main
  bun turbo ct
turbo 2.5.9-canary.4

• Packages in scope: @lib/deploy-ctl, app1, app2
• Running ct in 3 packages
• Remote caching disabled
app1:ct: cache miss, executing 15e36422ef67741f
app1:ct:
app1:ct: $ tsc --pretty --noEmit
@lib/deploy-ctl:ct: cache hit, replaying logs f213479b31b1fc4f
@lib/deploy-ctl:ct:
@lib/deploy-ctl:ct: $ tsc --noEmit
app2:ct: cache hit, replaying logs 5c4173d027ab7973
app2:ct:
app2:ct: $ tsc --pretty --noEmit

 Tasks:    3 successful, 3 total
Cached:    2 cached, 3 total
  Time:    600ms
```

`app2:ct` and `@lib/deploy-ctl:ctl` are getting a cache hits which is a sign that things are working how we'd hope for. Is there a way you're testing this differently?

**Comment by anthonyshew** [comment]
Now that this fix has been out for ~1 week, I'm comfortable with closing it up as a generalized "Bun doesn't work" issue.

If you are visiting this issue in the future and are experiencing a bug with Bun, please open a new issue.

Thank all of you for the feedback to help get this feature stabilized!
