### ISSUE TITLE
Lockfile changes when running `bun install --frozen-lockfile` on pruned repo

### ISSUE THREAD

**Issue by rtman** [vercel/turborepo#11171]
### Verify canary release

- [] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

Private repository, I have shared the bun lock files with turborepo however.

### Which canary version will you have in your reproduction?

2.6.1, the 2.6.2 canary versions are not published to npm yet.

### Environment information

```block
#10 0.183 turbo 2.6.1
#10 0.183 
#10 0.199 CLI:
#10 0.199    Version: 2.6.1
#10 0.199    Path to executable: /root/.bun/install/global/node_modules/turbo-linux-arm64/bin/turbo
#10 0.199    Daemon status: Not running
#10 0.199    Package manager: Not found
#10 0.199 
#10 0.199 Platform:
#10 0.199    Architecture: aarch64
#10 0.199    Operating system: linux
#10 0.199    WSL: false
#10 0.199    Available memory (MB): 6966
#10 0.199    Available CPU cores: 14
#10 0.199 
#10 0.199 Environment:
#10 0.199    CI: None
#10 0.199    Terminal (TERM): unknown
#10 0.199    Terminal program (TERM_PROGRAM): unknown
#10 0.199    Terminal program version (TERM_PROGRAM_VERSION): unknown
#10 0.199    Shell (SHELL): unknown
#10 0.199    stdin: false
#10 0.199
```

### Expected behavior

Expecting `bun install --frozen-lockfile --linker hoisted:` to complete successfully and not encounter a change in the lockfile causing an error.

### Actual behavior

```
 => [pruner 2/2] RUN turbo prune @repo/member-app-web --docker                                                                               2.7s 
 => [installer 2/4] COPY --from=pruner /usr/src/app/out/json/ .                                                                              0.0s 
 => [installer 3/4] COPY --from=pruner /usr/src/app/out/bun.lock ./bun.lock                                                                  0.0s 
 => ERROR [installer 4/4] RUN bun install --frozen-lockfile --linker hoisted                                                                 1.8s 
 => [builder 2/6] COPY --from=pruner /usr/src/app/out/full/ .                                                                                0.2s 
------                                                                                                                                            
 > [installer 4/4] RUN bun install --frozen-lockfile --linker hoisted:                                                                            
0.100 bun install v1.3.3 (274e01c7)                                                                                                               
0.114 Resolving dependencies                                                                                                                      
1.721 Resolved, downloaded and extracted [313]                                                                                                    
1.725 error: lockfile had changes, but lockfile is frozen                                                                                         
1.725 note: try re-running without --frozen-lockfile and commit the updated lockfile
------
Dockerfile:18
--------------------
  16 |     COPY --from=pruner /usr/src/app/out/json/ .
  17 |     COPY --from=pruner /usr/src/app/out/bun.lock ./bun.lock
  18 | >>> RUN bun install --frozen-lockfile --linker hoisted
  19 |     # RUN bun install --linker hoisted
  20 |     
--------------------
ERROR: failed to build: failed to solve: process "/bin/sh -c bun install --frozen-lockfile --linker hoisted" did not complete successfully: exit code: 1
```
### To Reproduce

I've provided the bun.lock from the pruned repo and the original repo via email to @anthonyshew 

### Additional context

Note I was unable to install the latest canary, 2.6.2-canary-1 or 0, as they are not available on npm yet. This looks to be similar to https://github.com/vercel/turborepo/issues/11007

**Comment by krzkz94** [comment]
Having a similar issue, the "nested dependencies fix" that was supposedly published in 2.6.1 doesn't work.

```
 => CACHED [pruner 3/3] RUN turbo prune @ex/api --docker                                       0.0s
 => CACHED [builder 1/4] COPY --from=pruner /app/out/json/ .                                   0.0s
 => CACHED [builder 2/4] COPY --from=pruner /app/out/bun.lock ./bun.lock

 > [builder 3/4] RUN bun install --frozen-lockfile:
0.109 bun install v1.3.3 (274e01c7)
0.173 570 |     "@trigger.dev/core": ["@trigger.dev/core@4.1.0", "", { "dependencies": { "@bugsn
0.173           ^
0.173 error: Failed to resolve prod dependency 'nanoid' for package '@trigger.dev/core'
0.173     at bun.lock:570:5
0.173 InvalidPackageInfo: failed to parse lockfile: 'bun.lock'
0.173 
0.173 warn: Ignoring lockfile
0.173 error: lockfile had changes, but lockfile is frozen
```

**Comment by preampinbut** [comment]
I'm also having this have use the og bun.lock ro fix this
I check into the generated bun.lock many dependencies got removed some have version changed cause bun to have a stroke

```dockerfile
COPY --from=prune --exclude=bun.lock /app/out/json/ .
COPY bun.lock ./bun.lock
```

**Comment by rtman** [comment]
@anthonyshew Do you (or your team) have any time to look at this? It's blocking for my team migrating to turbo.

## Maintainer's note

Please do not spam issues with any of:
- Requests for updates
  - When maintainers have updates to share, they post them. They do not wait for someone to ask for an update to do so.
- "+1" comments or similar that do not add any debugging information
  - If you want to express your interest in an issue, add a 👍 emoji to the original issue report.

Comments on GitHub Issues produce notifications for anyone participating on the issue, adding noise but no signal. Please consider contributing a pull request, adding a reproduction, or adding other novel information to the issue if you would like to aid in the Issue being closed.

**Comment by samishal1998** [comment]
It's also affecting our team, I had to remove pruning temporarily (but the image size is huge and CI takes forever)
In my case, I need to lock the version for certain deps, and if i don't use `--frozen-lockfile` the version will end up changing.

**Comment by anthonyshew** [comment]
Is everyone here using `node-linker: hoisted` or `--linker hoisted`?

**Comment by Palid** [comment]
I have `linker = "isolated"`, but it seems that linker issues do not matter with pruner. For pruning I just gave up on `ci` installs.
Already got this to fix on my todolist for dayjob, but it might take a while - there's a few higher priority things to work on first.

**Comment by anthonyshew** [comment]
The linker configuration matters quite a bit, but interesting to hear that you're getting problems with `linker = "isolated"`.

For anyone on this issue, I will only be able to work with complete reproductions to ensure your case is resolved. @rtman, I will try to work with your lockfile now but its possible a complete reproduction may be needed now that the lockfile parser is more matured out and we're getting out to the configuration edges.

**Comment by kylekz** [comment]
it's not a _minimal_ reproduction but my actual project has this problem with linker = "isolated" in bunfig.toml: https://github.com/teamreflex/cosmo-web/tree/refactor/tanstack-start

```bash
git clone git@github.com:teamreflex/cosmo-web.git
cd cosmo-web
git checkout refactor/tanstack-start
# in `apps/schedules/Dockerfile` add `--frozen-lockfile` to the install command
docker build -f apps/schedules/Dockerfile .
```
typesense-import also has the problem with an identical dockerfile

**Comment by arielweinberger** [comment]
@anthonyshew FWIF, I'm getting this issue with linked isolated/hoisted/unspecified

**Comment by rtman** [comment]
@anthonyshew for more context I am using the following in my bunfig.toml

```
linker = "isolated"
```

But in Ci I am using the following to install, it seemed to be needed when using turbo prune

```
bun install --frozen-lockfile --linker hoisted
```

If it helps I can experiment without `--linker hoisted`

I will see if I can provide a full repro, but since its private code I don't have a lot of hope there.

**Comment by kylekz** [comment]
noticed that 2.7.3 included a commit possibly related to this issue, so i tested and it still persists unfortunately

**Comment by maxvaljan** [comment]
have the same issue with linker isolated, any workarounds to make it work ?

**Comment by KhalidAlansary** [comment]
> have the same issue with linker isolated, any workarounds to make it work ?

Did you try this? https://github.com/vercel/turborepo/issues/11171#issuecomment-3610628738

**Comment by maxvaljan** [comment]
Repro repo (done with ai): https://github.com/maxvaljan/turbo-bun-prune-lockfile-repro

Steps (bun 1.3.5, turbo 2.7.5-canary.7):
1) bunx turbo@2.7.5-canary.7 prune web-ui --docker --out-dir out
2) cd out/json
3) bun install --lockfile-only --ignore-scripts

Actual:
error: Failed to resolve peer dependency 'expo-network' for package '@better-auth/expo'
InvalidPackageInfo: failed to parse lockfile: 'bun.lock'

Notes: apps/api depends on @better-auth/expo (catalog). Mobile workspaces provide expo-* peers in the root repo. After prune they’re not in scope, but the pruned bun.lock still includes @better-auth/expo, so bun errors while parsing the pruned lockfile.

**Comment by maxvaljan** [comment]
> #11171 (comment)

will try

**Comment by maxvaljan** [comment]
Update from our repo: root cause was the pruned graph pulling in a backend workspace that depends on @better-auth/expo, whose expo-* peer deps only exist in mobile workspaces removed by prune. Bun then rejects the pruned bun.lock with `Failed to resolve peer dependency 'expo-network'`.

Workaround that restored deterministic builds for us:
- remove `bun install --lockfile-only --ignore-scripts` from the prune stage (keep `bun install --frozen-lockfile` in the build stage)

After that it shoudl work, `bunx turbo prune <app> --docker` + `bun install --frozen-lockfile` succeeds

Repro repo still: https://github.com/maxvaljan/turbo-bun-prune-lockfile-repro

**Comment by ebramanti** [comment]
I am running into this issue as well, using isolated linker

**Comment by anthonyshew** [comment]
Hey, folks, all known reproductions from this issue should be taken care of at this point. Please open an issue with a reproduction if you run into something.
