### ISSUE TITLE
yarn 3 and turbo prune unable to find primary descriptor

### ISSUE THREAD

**Issue by ljukas** [vercel/turborepo#2146]
### What version of Turborepo are you using?

1.5.5

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

In a simple monorepo stup with two apps, running `turbo prune --scope=gateway --docker` will following message:

> #16 0.280 Generating pruned monorepo for gateway in /app/out
> #16 0.336  - Added gateway
> #16 0.351 panic: Unable to find primary descriptor typescript@npm:npm%3A^4.8.4
> #16 0.351
> #16 0.351 goroutine 19 [running]:
> #16 0.351 github.com/vercel/turborepo/cli/internal/lockfile.(*BerryLockfile).Subgraph(0x40009d8980, {0x4000271770, 0x1, 0x4000720040?}, {0x4000256000, 0x4fc, 0x78060a?})
> #16 0.351 	github.com/vercel/turborepo/cli/internal/lockfile/berry_lockfile.go:196 +0xe1c
> #16 0.351 github.com/vercel/turborepo/cli/internal/prune.(*prune).prune(0x400013bdf0, 0x400009e270)
> #16 0.351 	github.com/vercel/turborepo/cli/internal/prune/prune.go:207 +0x185c
> #16 0.351 github.com/vercel/turborepo/cli/internal/prune.GetCmd.func1(0x40000a9b80?, {0x77ec6b?, 0x2?, 0x2?})
> #16 0.351 	github.com/vercel/turborepo/cli/internal/prune/prune.go:62 +0xf0
> #16 0.351 github.com/spf13/cobra.(*Command).execute(0x40000a9b80, {0x40000300a0, 0x2, 0x2})
> #16 0.352 	github.com/spf13/cobra@v1.3.0/command.go:856 +0x4dc
> #16 0.352 github.com/spf13/cobra.(*Command).ExecuteC(0x40000a8000)
> #16 0.352 	github.com/spf13/cobra@v1.3.0/command.go:974 +0x360
> #16 0.352 github.com/spf13/cobra.(*Command).Execute(...)
> #16 0.352 	github.com/spf13/cobra@v1.3.0/command.go:902
> #16 0.352 github.com/vercel/turborepo/cli/internal/cmd.RunWithArgs.func1()
> #16 0.352 	github.com/vercel/turborepo/cli/internal/cmd/root.go:54 +0x34
> #16 0.352 created by github.com/vercel/turborepo/cli/internal/cmd.RunWithArgs
> #16 0.352 	github.com/vercel/turborepo/cli/internal/cmd/root.go:53 +0x240
> ------

This happens either in a Dockerfile following the with-docker example and directly in the repo without building inside docker.

### Expected Behavior

To output the pruned workspace in the /out folder.

### To Reproduce

I cannot reproduce it in the with-docker repo. Even with the gateway package.json instead of the package.json from the web folder.

When removing typescript as a devDependency in the root of my project I now instead get the same error as seen above but for the fsevents package. Which is a subDependency in another dependency.

**Comment by chris-olszewski** [comment]
I think I an idea of what the culprit of this is. Is there anyway you could post your `yarn.lock`? If you can't share your entire lockfile, just any entries that reference `typescript` would be helpful.

**Comment by ljukas** [comment]
Here is the yarn.lock in its entireity. Ive replaced out names with "expo-app" and "api-app" to protect the names :)

Thanks for looking into this.

[yarnlock.txt](https://github.com/vercel/turborepo/files/9698944/yarnlock.txt)

**Comment by chris-olszewski** [comment]
I think this is the same issue I ran into while adding support for pruning patched dependencies. [This update](https://github.com/vercel/turborepo/pull/2151/files#diff-79a10b80283685e5628eab75391e8240b2255f243799495517ab171b37c87053R496-R497) should fix the issue once it gets merged.

**Comment by chris-olszewski** [comment]
@ljukas Can you test out `turbo@1.5.6-canary.1` and see if the issue persists?

**Comment by ljukas** [comment]
I no longer get any errors running the prune command, thanks for the help @chris-olszewski

**Comment by TrySound** [comment]
I still get panic with turbo@1.5.6

panic: Unable to find primary descriptor typescript@npm:*

**Comment by nathanhammond** [comment]
@TrySound Can you file a new issue with more details and a reproduction?

Given that the OP in this issue reports their issue to be resolved it's almost certainly a separate issue.

Thanks!
